project:
  type: website

website:
  title: "Taara"
  search: false
  favicon: resources/site_logos/1x/Asset 2-8.png
  navbar:
    logo: resources/site_logos/SVG/Asset 2.svg
    logo-alt: "Taara"
    left:
      - href: index.qmd
        text: Home
      - href: ourteam.qmd
        text: About
      - href: contactus.qmd
        text: Contact
  page-footer:
    left: "© 2025 Taara"
    center: 
      - text: "hello@taara.io"
        href: "mailto:hello@taara.io"
    right:
      - text: "LinkedIn"
        href: "https://linkedin.com/company/taara-io"

format:
  html:
    search: false
    theme:
      - cosmo
    css: styles.css
    toc: false
